// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icibllzmaqaniepouehl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljaWJsbHptYXFhbmllcG91ZWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjU5MjcsImV4cCI6MjA2NDM0MTkyN30.aKtwEjXiSnW1b4UeKvZdSeZWnCFDSEo59yxWMxTxgmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);